//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public System.DateTime creationDate { get; set; }
        public System.Guid ownerId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public Nullable<System.Guid> gameId { get; set; }
        public Nullable<System.Guid> seasonId { get; set; }
        public Nullable<int> articleTypeId { get; set; }
        public string imageUrl { get; set; }
        public string subTitle { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Season Season { get; set; }
        public virtual User User { get; set; }
        public virtual ArticleType ArticleType { get; set; }
    }
}
