//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid ArticleId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> GameId { get; set; }
        public Nullable<System.Guid> SeasonId { get; set; }
        public Nullable<int> ArticleTypeId { get; set; }
        public string ImageUrl { get; set; }
        public string SubTitle { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual Game Game { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Season Season { get; set; }
        public virtual User User { get; set; }
    }
}
