//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionshipTeam
    {
        public System.Guid championshipTeamId { get; set; }
        public System.Guid championshipId { get; set; }
        public System.Guid teamId { get; set; }
    }
}
