//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionSeason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitionSeason()
        {
            this.LazyRankings = new HashSet<LazyRanking>();
            this.TeamCompetitionSeasons = new HashSet<TeamCompetitionSeason>();
        }
    
        public System.Guid competitionSeasonId { get; set; }
        public System.Guid competitionId { get; set; }
        public System.Guid seasonId { get; set; }
        public string lafaUrl { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Season Season { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LazyRanking> LazyRankings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamCompetitionSeason> TeamCompetitionSeasons { get; set; }
    }
}
