//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.Articles = new HashSet<Article>();
            this.PlayerGames = new HashSet<PlayerGame>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid HomeTeam { get; set; }
        public System.Guid AwayTeam { get; set; }
        public System.DateTime MatchDate { get; set; }
        public System.Guid SeasonId { get; set; }
        public string Championship { get; set; }
        public Nullable<int> HomeTeamScore { get; set; }
        public Nullable<int> AwayTeamScore { get; set; }
        public Nullable<int> ProlongHomeTeamScore { get; set; }
        public Nullable<int> ProlongAwayTeamScore { get; set; }
        public Nullable<int> PenaltyHomeTeamScore { get; set; }
        public Nullable<int> PenaltyAwayTeamScore { get; set; }
        public Nullable<System.Guid> ownerId { get; set; }
        public Nullable<System.Guid> CompetitionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Competition Competition1 { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerGame> PlayerGames { get; set; }
    }
}
