//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LazyRanking
    {
        public string Team { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> MatchPlayed { get; set; }
        public Nullable<int> MatchWon { get; set; }
        public Nullable<int> MatchDraw { get; set; }
        public Nullable<int> MatchLost { get; set; }
        public Nullable<int> GoalsScored { get; set; }
        public Nullable<int> GoalsAgainst { get; set; }
        public Nullable<int> GoalDifference { get; set; }
        public Nullable<int> Withdaw { get; set; }
        public Nullable<int> Penality { get; set; }
        public System.Guid RankingId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.Guid> CompetitionSeasonId { get; set; }
    
        public virtual CompetitionSeason CompetitionSeason { get; set; }
    }
}
