//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTeam
    {
        public System.Guid PlayerTeamId { get; set; }
        public System.Guid PlayerId { get; set; }
        public System.Guid TeamId { get; set; }
        public System.Guid SeasonId { get; set; }
        public Nullable<int> ChampionshipGoals { get; set; }
        public Nullable<int> NationalCupGoals { get; set; }
        public Nullable<int> RegionalCupGoals { get; set; }
        public Nullable<int> OtherCupGoals { get; set; }
        public Nullable<int> ChampionshipAssists { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
    }
}
