//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTeam
    {
        public System.Guid playerTeamId { get; set; }
        public System.Guid playerId { get; set; }
        public System.Guid teamId { get; set; }
        public System.Guid seasonId { get; set; }
        public Nullable<int> championshipGoals { get; set; }
        public Nullable<int> nationalCupGoals { get; set; }
        public Nullable<int> regionalCupGoals { get; set; }
        public Nullable<int> otherCupGoals { get; set; }
        public Nullable<int> championshipAssists { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
    }
}
