//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranking
    {
        public System.Guid championshipId { get; set; }
        public System.Guid teamId { get; set; }
        public int position { get; set; }
        public int points { get; set; }
        public int matchPlayed { get; set; }
        public int matchWon { get; set; }
        public int matchDraw { get; set; }
        public int matchLost { get; set; }
        public int goalsScored { get; set; }
        public int goalsAgainst { get; set; }
        public int goalDifference { get; set; }
        public int withdraw { get; set; }
        public int penality { get; set; }
        public Nullable<System.Guid> SeasonId { get; set; }
    }
}
