//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public System.Guid SponsorId { get; set; }
        public string Name { get; set; }
        public string LogoUrl { get; set; }
        public string SiteUrl { get; set; }
        public int OrderIndex { get; set; }
        public System.Guid OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
