//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballWebSiteApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamCompetitionSeason
    {
        public System.Guid teamCompetitionSeasonId { get; set; }
        public System.Guid teamId { get; set; }
        public System.Guid competitionSeasonId { get; set; }
        public string lafaName { get; set; }
        public string competitionGroup { get; set; }
    
        public virtual CompetitionSeason CompetitionSeason { get; set; }
        public virtual Team Team { get; set; }
    }
}
